import { KeyboardData } from "./data";

export const qwerty: KeyboardData = {
    name: "QWERTY",
    script: "latin",
    rows: [
        {
            height: 1,
            shift: 0,
            keys: [
                {
                    width: 1,
                    shift: 0,
                    key0: "q",
                    key1: "",
                    key2: "1",
                    key3: "",
                    key4: "esc",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "w",
                    key1: "~",
                    key2: "2",
                    key3: "@",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "e",
                    key1: "!",
                    key2: "3",
                    key3: "#",
                    key4: "loc €",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "r",
                    key1: "loc ₪",
                    key2: "4",
                    key3: "$",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "t",
                    key1: "",
                    key2: "5",
                    key3: "%",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "y",
                    key1: "",
                    key2: "6",
                    key3: "^",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "u",
                    key1: "",
                    key2: "7",
                    key3: "&",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "i",
                    key1: "",
                    key2: "8",
                    key3: "*",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "o",
                    key1: "loc accent_macron",
                    key2: "9",
                    key3: "(",
                    key4: ")",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "p",
                    key1: "",
                    key2: "0",
                    key3: "f11_placeholder",
                    key4: "f12_placeholder",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
            ],
        },
        {
            height: 1,
            shift: 0,
            keys: [
                {
                    width: 1,
                    shift: 0.5,
                    key0: "a",
                    key1: "tab",
                    key2: "`",
                    key3: "",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "s",
                    key1: "loc accent_ring",
                    key2: "",
                    key3: "loc ß",
                    key4: "loc accent_ogonek",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "d",
                    key1: "loc accent_grave",
                    key2: "loc £",
                    key3: "loc accent_aigu",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "f",
                    key1: "loc accent_dot_above",
                    key2: "",
                    key3: "",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "g",
                    key1: "loc accent_caron",
                    key2: "-",
                    key3: "_",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "h",
                    key1: "",
                    key2: "=",
                    key3: "+",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "j",
                    key1: "loc accent_trema",
                    key2: "loc accent_circonflexe",
                    key3: "{",
                    key4: "}",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "k",
                    key1: "loc accent_double_aigu",
                    key2: "",
                    key3: "[",
                    key4: "]",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "l",
                    key1: "",
                    key2: "|",
                    key3: "\\",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
            ],
        },
        {
            height: 1,
            shift: 0,
            keys: [
                {
                    width: 1.5,
                    shift: 0,
                    key0: "shift",
                    key1: "",
                    key2: "loc capslock",
                    key3: "",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "z",
                    key1: "",
                    key2: "",
                    key3: "",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "x",
                    key1: "",
                    key2: "",
                    key3: "",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "c",
                    key1: "loc accent_cedille",
                    key2: "<",
                    key3: ".",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "v",
                    key1: "",
                    key2: ">",
                    key3: ",",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "b",
                    key1: "",
                    key2: "?",
                    key3: "/",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "n",
                    key1: "loc accent_tilde",
                    key2: ":",
                    key3: ";",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1,
                    shift: 0,
                    key0: "m",
                    key1: "",
                    key2: '"',
                    key3: "'",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
                {
                    width: 1.5,
                    shift: 0,
                    key0: "backspace",
                    key1: "",
                    key2: "delete",
                    key3: "",
                    key4: "",
                    key5: "",
                    key6: "",
                    key7: "",
                    key8: "",
                    slider: false,
                },
            ],
        },
    ],
    bottomRow: true,
};

export const keyboards: Record<string, KeyboardData> = {
    Blank: { name: "Custom Layout", script: "", bottomRow: true, rows: [] },
    QWERTY: qwerty,
};
