# SourceHut Build Manifest
image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
    - nodejs
    - yarn
    - hut
environment:
    site: unexpected-keyboard-layout-editor.lixquid.com
sources:
    - https://github.com/lixquid/app-unexpected-keyboard-layout-editor
tasks:
    - build: |
          cd *
          yarn install
          yarn build
    - package: |
          set +x
          if [ -z "$OAUTH2_TOKEN" ]; then
              echo "Skipping build"
              exit 0
          fi
          set -x
          cd */dist
          tar czvf ../dist.tgz *
          hut pages publish -d $site ../dist.tgz
